name: SimpleNPC
version: '${project.version}'
main: org.gotitim.simplenpc.SimpleNPC
api-version: 1.18
authors: [ gotitim ]
commands:
  npc:
    description: npc command
    permission: simplenpc.cmd
permissions:
  simplenpc.cmd:
    default: op
    description: NPC management command